# Generated by Django 4.0.2 on 2024-03-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='completed',
        ),
    ]
